env:
  browser: true
  es2021: true
extends:
  - eslint:recommended
  - plugin:react/recommended
  - prettier

plugins:
  - react
parserOptions:
  ecmaVersion: latest
  sourceType: module
rules: 
  semi: off
  react/react-in-jsx-scope: off
 # Add or customize your ESLint rules here
  react/jsx-filename-extension:
    - error
    - extensions:
      - ".js"
      - ".jsx"
